"""Corpus manifest types.

The manifest is the contract between three things that must agree: the generator that
produces the synthetic documents, the extraction step that reads typed fields back out
of them, and the evaluation suite that grades answers against known ground truth.

Without a manifest, "did extraction work?" and "was that answer correct?" are both
judgement calls. With one, they are assertions.
"""

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, Field

from src.domain.entities.deal import Deal, Sensitivity


class DocumentType(StrEnum):
    """Kinds of document in the synthetic corpus.

    Modelled on the document types a public finance desk works with. All content is
    generated; nothing is retrieved from any disclosure system.
    """

    OFFICIAL_STATEMENT = "official_statement"
    CONTINUING_DISCLOSURE = "continuing_disclosure"
    MATERIAL_EVENT_NOTICE = "material_event_notice"
    INTERNAL_PRICING_MEMO = "internal_pricing_memo"


class DefectKind(StrEnum):
    """Deliberate defects planted in the corpus.

    A guardrail that fires only sometimes cannot be demonstrated. Each defect exists to
    force a specific behaviour on every run.
    """

    MISSING_CALL_PROVISION = "missing_call_provision"
    """Forces an evidence gap rather than an invented redemption date."""

    CONFLICTING_FIGURE = "conflicting_figure"
    """Two documents disagree, so groundedness scoring has something real to catch."""

    LATE_DISCLOSURE = "late_disclosure"
    """A filing past its deadline, giving the compliance path a genuine finding."""

    STALE_FINANCIALS = "stale_financials"
    """Data old enough that using it uncritically would be wrong."""


class PlantedDefect(BaseModel):
    """A defect deliberately introduced into a document."""

    kind: DefectKind
    description: str = Field(description="What was planted, in plain language.")
    expected_behaviour: str = Field(
        description=(
            "What the system must do when it encounters this. Asserted by the "
            "evaluation suite, and narrated during the demonstration."
        )
    )
    related_document_id: str | None = Field(
        default=None,
        description="The other document involved, for conflicts.",
    )


class DocumentEntry(BaseModel):
    """One document in the corpus, with its ground truth."""

    document_id: str
    title: str
    document_type: DocumentType
    sensitivity: Sensitivity
    blob_path: str
    page_count: int

    allowed_group_claims: list[str] = Field(
        default_factory=list,
        description=(
            "Group claims permitted to retrieve this document. Empty means public-side, "
            "visible to every caller. Private-side documents name the deal-team group."
        ),
    )

    expected_deal: Deal | None = Field(
        default=None,
        description=(
            "Ground truth for extraction. Comparing extracted fields against this is "
            "what makes 'extraction works' an assertion rather than an impression."
        ),
    )

    defects: list[PlantedDefect] = Field(default_factory=list)


class CorpusManifest(BaseModel):
    """The full corpus and its ground truth."""

    generated_at: str
    generator_version: str = "1.0.0"
    documents: list[DocumentEntry]
    subject_deal: Deal | None = Field(
        default=None,
        description="Proposed synthetic financing used as the orchestrator's comparison subject.",
    )
    subject_allowed_group_claims: list[str] = Field(
        default_factory=list,
        description="Group claims allowed to retrieve the proposed private-side financing.",
    )

    # Recorded in the artifact itself so provenance travels with the data, rather than
    # relying on a reader finding the repository documentation.
    provenance: str = (
        "All documents are synthetic and generated by this repository. No content was "
        "retrieved from MSRB EMMA or any other disclosure system. Issuers are fictional."
    )

    def public_documents(self) -> list[DocumentEntry]:
        """Documents visible to a caller with no special entitlements."""
        return [d for d in self.documents if d.sensitivity is Sensitivity.PUBLIC]

    def documents_with_defects(self) -> list[DocumentEntry]:
        """Documents carrying at least one planted defect."""
        return [d for d in self.documents if d.defects]
